spring.application.name=biblioteca-api

# --- Configuración de la Conexión a Oracle ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=biblioteca_user
spring.datasource.password=${DB_APP_PASSWORD}

# --- Configuración de JPA (útil para desarrollo) ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# --- Prefix ---
server.servlet.context-path=/api