spring.application.name=biblioteca-api

# --- Configuraci�n de la Conexi�n a Oracle cambiar a la tuya es del usuario donde se crearan las tablas y conectaremos  ---
# --- Nota: Asegurate de tener el servicio de Oracle en ejecuci�n y la base de datos creada ---
# --- Cambiar el puerto si es necesario (1521 es el predeterminado) ---
# --- Cambiar XEPDB1 por el nombre de tu servicio de base de datos si es diferente ---
# --- Cambiar Usuario y contrasena luego de crear como system desde tu oracle ---
# --- Para una ejecucion rapida remover esa variable de entorno y poner la contrasena directamente del usuario creado, tambien recordar darle todos los permisos para poder ejecutar nuestros scripts de la raiz ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1524/XEPDB1
spring.datasource.username=biblioteca_testing
spring.datasource.password=${DB_APP_PASSWORD}

# --- Configuraci�n de JPA (�til para desarrollo) ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# --- Prefix ---
server.servlet.context-path=/api